version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ai_stats
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  stats-service:
    build:
      context: ../stats-service
      dockerfile: Dockerfile
    container_name: stats-service
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: ai_stats
      GRPC_PORT: 50051
    ports:
      - "50051:50051"

  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - stats-service
    environment:
      GRPC_SERVER: stats-service:50051
      HTTP_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  postgres_data:
