services:
  db:
    image: postgres:17.3-alpine
    container_name: postgres_db
    restart: always
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=stats
    volumes:
      - postgres_data:/var/lib/postgresql/data

  stats-service:
    build:
      context: stats-service
      dockerfile: Dockerfile
    container_name: stats-service
    depends_on:
      - db
    environment:
      - DB_SOURCE=postgresql://root:secret@db:5432/stats?sslmode=disable
      - GRPC_PORT=9090
    entrypoint: ["/app/wait-for.sh", "db:5432", "--", "/app/start.sh"]
    command: ["./main"]
    

  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - stats-service
    environment:
      - GRPC_SERVER=stats-service:9090
      #- HTTP_PORT=8080
    ports:
      - "8080:8080"

volumes:
  postgres_data:
