// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateUser(ctx context.Context, name string) (User, error)
	GetStats(ctx context.Context, arg GetStatsParams) ([]GetStatsRow, error)
	PostCall(ctx context.Context, arg PostCallParams) (Stat, error)
}

var _ Querier = (*Queries)(nil)
