// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateService(ctx context.Context, arg CreateServiceParams) (int64, error)
	GetCalls(ctx context.Context, arg GetCallsParams) ([]GetCallsRow, error)
	PostCall(ctx context.Context, arg PostCallParams) (Stat, error)
}

var _ Querier = (*Queries)(nil)
