// Code generated by sqlc. DO NOT EDIT.
// source: service.sql

package db

import (
	"context"
)

const createService = `-- name: CreateService :one
INSERT INTO services (name, description, created_at)
VALUES ($1, $2, NOW())
RETURNING id
`

type CreateServiceParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createService, arg.Name, arg.Description)
	var id int64
	err := row.Scan(&id)
	return id, err
}
