// Code generated by sqlc. DO NOT EDIT.
// source: service.sql

package db

import (
	"context"
)

const createService = `-- name: CreateService :one
INSERT INTO services (name, description, created_at)
VALUES ($1, $2, NOW())
RETURNING id, name, description, price, created_at
`

type CreateServiceParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService, arg.Name, arg.Description)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}
