// Code generated by sqlc. DO NOT EDIT.

package model

import (
	"time"
)

type Stat struct {
	UserID    int64    
	ServiceID int64     
	Count     int64     
	CreatedAt time.Time 
}

type PostCallRequest struct {
	UserId        int64  
	ServiceId     int64 
}

type GetStatsRequest struct {
	UserId        int64 
	ServiceId     int64 
	Page          int32 
	Limit         int32  
}

type GetStatsResponse struct {
	Stats         []*StatRecord          
}

type StatRecord struct {
    UserId        int64                
    ServiceId     int64                  
    Count         int64                  
}